# Generated by Django 3.2.8 on 2021-10-06 16:10

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modify', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('category', models.CharField(max_length=30, unique=True, verbose_name='Categoria')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modify', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('item', models.CharField(max_length=120, verbose_name='Item')),
                ('document', models.FileField(blank=True, upload_to=core.models.get_file_path, verbose_name='Documento')),
                ('topic', models.TextField(blank=True, verbose_name='Link / Texto')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorias')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
    ]
